-- ── Better Auth tables (generated by `@better-auth/cli generate`, made idempotent).
-- Created first so entries.owner_id can FK to "user"(id).
CREATE TABLE IF NOT EXISTS "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);
CREATE TABLE IF NOT EXISTS "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);
CREATE INDEX IF NOT EXISTS "session_userId_idx" on "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" on "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" on "verification" ("identifier");

CREATE TABLE IF NOT EXISTS entries (
  id   TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS picks (
  id                SERIAL PRIMARY KEY,
  entry_id          TEXT NOT NULL REFERENCES entries(id),
  week              INTEGER NOT NULL,
  team              TEXT NOT NULL,
  win_prob_at_pick  DOUBLE PRECISION,
  picked_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (entry_id, team),
  UNIQUE (entry_id, week)
);

-- Latest win probability captured while the picked game was still upcoming
-- (refreshed on every stats refresh, then frozen once the game kicks off).
ALTER TABLE picks ADD COLUMN IF NOT EXISTS win_prob_pregame DOUBLE PRECISION;

CREATE TABLE IF NOT EXISTS cache (
  key        TEXT PRIMARY KEY,
  payload    JSONB NOT NULL,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE entries ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}';

-- Multi-tenancy: every entry belongs to exactly one Better Auth user. Added nullable
-- so existing rows migrate cleanly, then backfilled and set NOT NULL (see plan T13/T20).
ALTER TABLE entries ADD COLUMN IF NOT EXISTS owner_id TEXT REFERENCES "user"(id);
CREATE INDEX IF NOT EXISTS entries_owner_id_idx ON entries (owner_id);

CREATE TABLE IF NOT EXISTS pick_overrides (
  entry_id TEXT NOT NULL REFERENCES entries(id) ON DELETE CASCADE,
  week     INTEGER NOT NULL,
  outcome  TEXT NOT NULL CHECK (outcome IN ('survived', 'out', 'revived')),
  PRIMARY KEY (entry_id, week)
);

-- Widen the outcome check on tables created before 'revived' existed.
ALTER TABLE pick_overrides DROP CONSTRAINT IF EXISTS pick_overrides_outcome_check;
ALTER TABLE pick_overrides ADD CONSTRAINT pick_overrides_outcome_check
  CHECK (outcome IN ('survived', 'out', 'revived'));

-- Every entry now has an owner (backfilled from the old seed rows) so enforce it.
-- The old ownerless seed INSERT was removed. Entries are created per user via the app.
ALTER TABLE entries ALTER COLUMN owner_id SET NOT NULL;

-- Web Push subscriptions (one row per browser/device a user enabled notifications on).
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  endpoint   TEXT NOT NULL UNIQUE,
  p256dh     TEXT NOT NULL,
  auth       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_id_idx ON push_subscriptions (user_id);

-- Maps a Klaviyo Customer Agent conversation to the user who owns it, so a transcript read
-- (GET /api/chat?conversationId=) can be authorized to that user. We store only the mapping,
-- not the messages — Klaviyo is the system of record for the transcript itself.
CREATE TABLE IF NOT EXISTS chat_conversations (
  conversation_id TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS chat_conversations_user_id_idx ON chat_conversations (user_id);

-- Dedup for pick notifications: one row per (entry, week, event_type) once that notification is
-- sent. event_type is 'final' (win/loss) plus live events 'halftime' and 'close'. The ALTERs
-- generalize older installs that keyed only on (entry_id, week); existing rows become 'final',
-- preserving win/loss dedup history.
CREATE TABLE IF NOT EXISTS pick_result_notifications (
  entry_id    TEXT NOT NULL,
  week        INTEGER NOT NULL,
  result      TEXT NOT NULL,
  notified_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (entry_id, week)
);
ALTER TABLE pick_result_notifications ADD COLUMN IF NOT EXISTS event_type TEXT NOT NULL DEFAULT 'final';
ALTER TABLE pick_result_notifications DROP CONSTRAINT IF EXISTS pick_result_notifications_pkey;
ALTER TABLE pick_result_notifications ADD PRIMARY KEY (entry_id, week, event_type);

-- Per-user "notify me about" preferences. notify_final = win/loss results; notify_live =
-- in-game updates (halftime, close game). Absent row = both on (push is already opt-in).
CREATE TABLE IF NOT EXISTS notification_prefs (
  user_id      TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
  notify_final BOOLEAN NOT NULL DEFAULT true,
  notify_live  BOOLEAN NOT NULL DEFAULT true,
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
